admin_rs/urls.py
from django.urls import include,path
from .views import form_admin,homepage
app_name='admin_rs'
urlpatterns =[
    path('register/',form_admin,name='form_admin'),
    path('profile/',homepage,name='admin_profile')
    ]

dokter_rscabang/urls.py
from django.urls import path
from .views import read,delete,create,update

app_name = 'dokter_rscabang'

urlpatterns = [
    path('register/', create, name='register'),
    path('daftardokter/', read, name='daftar'),
    path('deletedokter/<str:id>/',delete,name='delete-dokter'),
    path('updatedokter/<str:id>/',update,name='update-dokter')
]

layanan_poli/urls.py
from django.urls import path
from .views import (createl, updatel, readl, deletel, updatej, readj, deletej)

app_name = 'layanan_poli'

urlpatterns = [
    path('create_layanan/', createl, name='layanan_create'),
    path('update_layanan/<str:id>/', updatel, name='layanan_update'),
    path('read_layanan/', readl, name='layanan_read'),
    path('delete_layanan/<str:id>/', deletel, name='layanan_delete'),

    path('update_jadwal/<str:id>/', updatej, name='jadwal_update'),
    path('read_jadwal/', readj, name='jadwal_read'),
    path('delete_jadwal/<str:id>/', deletej, name='jadwal_delete')
]

medikago/urls.py
from django.urls import include,path

urlpatterns = [
    path('', include('pengguna.urls')),
    path('rs_cabang/',include('rs_cabang.urls')),
    path('sesi_konsultasi/',include('sesi_konsultasi.urls')),
    path('admin_rs/', include('admin_rs.urls')),
    path('tindakan/', include('tindakan.urls')),
    path('dokter/', include('dokter_rscabang.urls')),
    path('layanan_poli/', include('layanan_poli.urls')),
    path('transaksi/', include('transaksi.urls')),
]

pengguna/urls.py
from django.urls import path
from . import views

app_name = 'pengguna'

urlpatterns = [
    path('', views.general_profile, name='profile'),
    path('redirect/',views.register_redirect,name='redirect'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('register/<str:role>/', views.register_role, name='register-role'),
    path('logout/', views.logout, name='logout'),
]

admin_rs/models.py
from django.db import models

# Create your models here.

admin_rs/forms.py
from django import forms

class DateInput(forms.DateInput):
    input_type = 'date'
    
class adminForm(forms.Form):
    username=forms.CharField(label='Username:', max_length=50,widget=forms.TextInput(attrs={'placeholder':'Isi username Anda di sini (maks 50 karakter)'}))
    password=forms.CharField(label='Password:',max_length=128,widget=forms.PasswordInput(attrs={'placeholder':'Isi pass Anda di sini (maks 128 karakter)'}))
    no_identitas=forms.CharField(label='Nomor identitas:',max_length=50,widget=forms.TextInput(attrs={'placeholder':'Isi no identitas Anda(KTP, Kartu pelajar,dsb) di sini (maks 50 karakter)'}))
    nama_lengkap=forms.CharField(label='Nama lengkap:',max_length=50,widget=forms.TextInput(attrs={'placeholder':'Isi nama lengkap Anda di sini (maks 50 karakter)'}))
    tanggal_lahir=forms.DateField(label='Tanggal lahir:',widget=DateInput(attrs={'placeholder':'mm/dd/yyyy'}))
    email=forms.CharField(label='Email:', max_length=50,widget=forms.TextInput(attrs={'placeholder':'Isi email Anda di sini (maks 50 karakter dengan format <akun>@<domain email>)'}))
    alamat=forms.CharField(label='Alamat:',widget=forms.Textarea(attrs={'placeholder':'Isi alamat rumah/kost/kontrakan Anda di sini'}))

admin_rs/views.py
from django.shortcuts import render,reverse,redirect
from .forms import adminForm
from django.db import connection
from pengguna.views import auth_login
from django.http import HttpResponse
from django.core.exceptions import PermissionDenied
import random as r 

def assign_rs():
    lst=[]
    with connection.cursor() as cursor:
        cursor.execute("SELECT kode_rs FROM RS_CABANG")
        data=cursor.fetchall()
        for i in range(len(data)):
            lst.append(data[i][0])
    return r.choice(lst)

def validate_email(email):
    result=None
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM PENGGUNA WHERE email=%s",[email])
        result=cursor.fetchone()
    return result == None

def validate_username(username):
    result=None
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM PENGGUNA WHERE username=%s",[username])
        result=cursor.fetchone()
    return result == None

def validate_id(nomor_id):
    result=None
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM PENGGUNA WHERE nomor_id=%s",[nomor_id])
        result=cursor.fetchone()
    return result == None

def generate_np():
    value=''
    with connection.cursor() as cursor:
        cursor.execute("SELECT nomor_pegawai FROM ADMINISTRATOR ORDER BY nomor_pegawai DESC LIMIT 1")
        value=str(int(cursor.fetchone()[0])+1)
    if(value == None):
        return 0
    return value

def form_admin(request):
    if(request.session.is_empty()):
        form=adminForm()
        if (request.method=='POST'):
            form=adminForm(request.POST)
            if(form.is_valid()):
                username=form.cleaned_data['username']
                password=form.cleaned_data['password']
                nomor_id=form.cleaned_data['no_identitas']
                nama_lengkap=form.cleaned_data['nama_lengkap']
                tanggal_lahir=form.cleaned_data['tanggal_lahir']
                email=form.cleaned_data['email']
                alamat=form.cleaned_data['alamat']
                if (not validate_email(email)) or (not validate_username(username)) or (not validate_id(nomor_id)):
                    if( not validate_email(email)):
                        form.add_error('email','Email cant be duplicate!')
                    if( not validate_username(username)):
                        form.add_error('username','Username is already exist!')
                    if( not validate_id(nomor_id)):
                        form.add_error('no_identitas','Id number is already exist!')
                    context = {'form':form}
                    return render(request,'generic_regist.html',{'form':form})
                with connection.cursor() as cursor:
                    cursor.execute("INSERT INTO PENGGUNA VALUES(%s, %s, %s, %s, %s,%s,%s)", [email, username, password, nama_lengkap, nomor_id, tanggal_lahir,alamat])
                    no_pegawai=generate_np()
                    kode_rs=assign_rs()
                    cursor.execute("INSERT INTO ADMINISTRATOR VALUES (%s,%s,%s)",[no_pegawai,username,kode_rs])
                    auth_login(request,username,password)
                    request.session['success_registered']=True
                    return redirect('pengguna:redirect')
        context={
            'form':form,
            'title':"Form Registrasi Administrator",
            'target_url': reverse('admin_rs:form_admin')
        }
        return render(request,'generic_regist.html',context)
    else:
        return HttpResponse(status=404)

def homepage(request):
    if(request.session.is_empty()):
        return redirect("pengguna:profile")
    else:
        if(request.session['role']=='admin'):
            context={
                        'username':request.session['username'],
                        'nomor_id':request.session['nomor_id'],
                        'nama_lengkap':request.session['nama_lengkap'],
                        'tanggal_lahir':request.session['tanggal_lahir'],
                        'alamat':request.session['alamat'],
                        'email':request.session['email']
                    }
            return render(request,'profile_admin.html',context)
        else:
            raise PermissionDenied

admin_rs/templates/base_admin.html
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        @media only screen and (max-width: 600px) {
            h1{
                font-size: 30px;
            }
            p{
                font-size: 10px;
            }
        }
        body{
            margin-top:72px;
        }
    </style>
</head>
{% include "navbar-admin.html"%}
<body>
  {% block content %}
  {% endblock %}
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
 {% block script%}
 {% endblock %}
</body>
<footer class="page-footer font-small blue">

  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="#"> Kelompok 69</a>
  </div>
</footer>

admin_rs/templates/navbar-admin.html
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">MEDIKAGO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/admin_rs/profile/">Profil</a>
      </li>
     <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sesi Konsultasi
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/sesi_konsultasi/create/">Buat Sesi Konsultasi</a>
          <a class="dropdown-item" href="/sesi_konsultasi/read/">Daftar Sesi Konsultasi</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Poliklinik
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'layanan_poli:layanan_create' %}">Buat Layanan Poliklinik</a>
          <a class="dropdown-item" href="{% url 'layanan_poli:layanan_read' %}">Daftar Layanan Poliklinik</a>
          <a class="dropdown-item" href="{% url 'layanan_poli:jadwal_read' %}">Daftar Jadwal Poliklinik</a>
        </div>
      </li>

       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          RS Cabang
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/rs_cabang/create/">Buat RS Cabang</a>
          <a class="dropdown-item" href="/rs_cabang/read/">Daftar RS Cabang</a>
          <a class="dropdown-item" href="{%url 'dokter_rscabang:register' %}">Daftarkan Dokter</a>
          <a class="dropdown-item" href="{%url 'dokter_rscabang:daftar' %}">Daftar Dokter-RS Cabang</a>
          <a class="dropdown-item" href="#">Daftarkan Administrator</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Tindakan
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/tindakan/create/">Buat Tindakan</a>
          <a class="dropdown-item" href="/tindakan/">Daftar Tindakan</a>
          <a class="dropdown-item" href="/tindakan/poliklinik/create/">Buat Tindakan Poliklinik</a>
          <a class="dropdown-item" href="/tindakan/poliklinik/">Daftar Tindakan Poliklinik</a>
        </div>
      </li>
    


      <li class="nav-item">
        <a class="nav-link" href="/transaksi/read/">Daftar Transaksi</a>
      </li>
    </ul>
    <a class="btn btn-sm btn-outline-success" href="{% url 'pengguna:logout' %}">Logout</a>
  </div>
</nav>

admin_rs/templates/profile_admin.html
{% extends 'base.html' %}
{% block content%}
  <div class="container">
      <h1>Profile Administrator</h1>
        <div>
            <div class="row">
            <div class="col-4">Username</div>
            <div class="col-8">{{ username }}</div>
            </div>
            <div class="row mt-3">
            <div class="col-4">Nomor Identitas</div>
            <div class="col-8">{{ nomor_id }}</div>
            </div>
            <div class="row mt-3">
            <div class="col-4">Nama Lengkap</div>
            <div class="col-8">{{ nama_lengkap }}</div>
            </div>
            <div class="row mt-3">
            <div class="col-4">Tanggal Lahir</div>
            <div class="col-8">{{ tanggal_lahir }}</div>
            </div>
            <div class="row mt-3">
            <div class="col-4">Email</div>
            <div class="col-8">{{ email }}</div>
            </div>
            <div class="row mt-3">
            <div class="col-4">Alamat</div>
            <div class="col-8">{{ alamat }}</div>
            </div>
        </div>
  </div>
{%endblock%}