admin_rs/urls.py
from django.urls import include,path
from .views import form_admin,homepage
app_name='admin_rs'
urlpatterns =[
    path('register/',form_admin,name='form_admin'),
    path('profile/',homepage,name='admin_profile')
    ]

layanan_poli/urls.py
from django.urls import path
from .views import (createl, updatel, readl, deletel, updatej, readj, deletej)

app_name = 'layanan_poli'

urlpatterns = [
    path('create_layanan/', createl, name='layanan_create'),
    path('update_layanan/<str:id>/', updatel, name='layanan_update'),
    path('read_layanan/', readl, name='layanan_read'),
    path('delete_layanan/<str:id>/', deletel, name='layanan_delete'),

    path('update_jadwal/<str:id>/', updatej, name='jadwal_update'),
    path('read_jadwal/', readj, name='jadwal_read'),
    path('delete_jadwal/<str:id>/', deletej, name='jadwal_delete')
]

medikago/urls.py
from django.urls import include,path

urlpatterns = [
    path('', include('pengguna.urls')),
    path('rs_cabang/',include('rs_cabang.urls')),
    path('sesi_konsultasi/',include('sesi_konsultasi.urls')),
    path('admin_rs/', include('admin_rs.urls')),
    path('tindakan/', include('tindakan.urls')),
    path('dokter/', include('dokter_rscabang.urls')),
    path('layanan_poli/', include('layanan_poli.urls')),
    path('transaksi/', include('transaksi.urls')),
]

pengguna/urls.py
from django.urls import path
from . import views

app_name = 'pengguna'

urlpatterns = [
    path('', views.general_profile, name='profile'),
    path('redirect/',views.register_redirect,name='redirect'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('register/<str:role>/', views.register_role, name='register-role'),
    path('logout/', views.logout, name='logout'),
]

rs_cabang/urls.py
from django.urls import include,path
from .views import form_page,update,read,delete
app_name='rs_cabang'
urlpatterns =[
    path('create/',form_page,name='rs_form'),
    path('update/<str:id>/', update, name='rs_form_update'),
    path('delete/<str:id>/', delete, name='rs_delete'),
    path('read/',read,name='rs_form_read')
    ]

tindakan/urls.py
from django.urls import path
from . import views

app_name = 'tindakan'

urlpatterns = [
    path('poliklinik/create/', views.poli_create, name='poli-create'),
    path('poliklinik/', views.poli_read, name="poli-read"),
    path('poliklinik/update/<str:pk>/', views.poli_update, name="poli-update"),
    path('poliklinik/delete/<str:pk>/', views.poli_delete, name="poli-delete"),
    path('create/', views.create, name='create'),
    path('', views.read, name="read"),
    path('update/<str:id_konsul>/<str:no_urut>/', views.update, name='update'),
    path('delete/<str:id_konsul>/<str:no_urut>/', views.delete, name='delete'),
]

transaksi/urls.py
from django.urls import include,path
from .views import form,update,read,delete
app_name='transaksi'
urlpatterns =[
    path('create/',form,name='transaksi_form'),
    path('update/<str:id>/',update,name='transaksi_update'),
    path('read/',read,name='transaksi_read'),
    path('delete/<str:id>/',delete,name='transaksi_delete')
    ]

pengguna/models.py
from django.db import models

pengguna/forms.py
from django import forms
from django.db import connection


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegisterPenggunaForm(LoginForm):
    nomor_identitas = forms.CharField()
    nama_lengkap = forms.CharField()
    tanggal_lahir = forms.DateField()
    email = forms.EmailField()
    alamat = forms.CharField(widget=forms.Textarea(attrs={'rows': 3}))

    def save(self):
        with connection.cursor() as cursor:
            cursor.execute(
                'INSERT INTO pengguna VALUES (%s, %s, %s, %s, %s, %s, %s)',
                (
                    self.cleaned_data['email'],
                    self.cleaned_data['username'],
                    self.cleaned_data['password'],
                    self.cleaned_data['nama_lengkap'],
                    self.cleaned_data['nomor_identitas'],
                    self.cleaned_data['tanggal_lahir'],
                    self.cleaned_data['alamat'],
                ))

class RegisterPasienForm(RegisterPenggunaForm):
    alergi = forms.MultipleChoiceField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # disable option validation for alergi
        if len(args) >= 1:
            print([(x, x) for x in args[0].getlist('alergi')])
            self.fields['alergi'].choices = [(x, x) for x in args[0].getlist('alergi')]

    def save(self):
        super().save()

        with connection.cursor() as cursor:
            # get last asuransi
            cursor.execute('SELECT nama FROM asuransi LIMIT 1')
            asuransi = cursor.fetchone()[0]

            # get last pasien id
            cursor.execute(
                'SELECT no_rekam_medis FROM pasien ORDER BY no_rekam_medis DESC LIMIT 1')
            try:
                prev_id = cursor.fetchone()[0]
            except IndexError:
                prev_id = '10000000'
            next_id = str(int(prev_id) + 1)

            # store pasien
            cursor.execute(
                'INSERT INTO pasien VALUES (%s, %s, %s)',
                (
                    next_id,
                    self.cleaned_data['username'],
                    asuransi,
                ))

            # store alergi
            for nama_alergi in self.cleaned_data['alergi']:
                cursor.execute(
                    'INSERT INTO alergi_pasien VALUES (%s, %s)',
                    (next_id, nama_alergi))


class RegisterDokterForm(RegisterPenggunaForm):
    no_sip = forms.CharField()
    spesialisasi = forms.CharField()

    def save(self):
        super().save()
        with connection.cursor() as cursor:
            cursor.execute('SELECT id_dokter FROM dokter ORDER BY id_dokter DESC LIMIT 1')
            try:
                prev_id = cursor.fetchone()[0]
            except IndexError:
                prev_id = 'D0'
            next_id = prev_id[:1] + str(int(prev_id[1:]) + 1)

            cursor.execute(
                'INSERT INTO dokter VALUES (%s, %s, %s, %s)',
                (
                    next_id,
                    self.cleaned_data['username'],
                    self.cleaned_data['no_sip'],
                    self.cleaned_data['spesialisasi'],
                ))

pengguna/views.py
from django.shortcuts import redirect, render, reverse
from django.http import HttpResponseNotFound
#from django.contrib.auth import (authenticate, login as django_login,logout as django_logout)
from .forms import LoginForm, RegisterPasienForm, RegisterDokterForm
from django.db import connection
from django.core.serializers.json import DjangoJSONEncoder
import json

register_forms = {
    'pasien': RegisterPasienForm,
    'dokter': RegisterDokterForm,
}


def register_redirect(request):
    if request.session.is_empty():
        return redirect('pengguna:profile')
    else:
        if(request.session['success_registered']):
            context={'role':request.session['role']}
            request.session['success_registered']=False
            return render(request,'redirect_success.html',context)
        else:
            return redirect('pengguna:profile')


def general_profile(request):
    if 'username' not in request.session:
        return render(request,'index.html')
    elif request.session['role'] == 'admin':
        return redirect('admin_rs:admin_profile')

    context = {
        'data': {
            'Username': request.session['username'],
            'Nomor Identitas': request.session['nomor_id'],
            'Nama Lengkap': request.session['nama_lengkap'],
            'Tanggal Lahir': request.session['tanggal_lahir'],
            'Email': request.session['email'],
            'Alamat': request.session['alamat'],
        }
    }
    if request.session.get('role') == 'pasien':
        with connection.cursor() as cursor:
            cursor.execute(
                'SELECT no_rekam_medis FROM pasien WHERE username = %s',
                (request.session['username'],))
            no_rekam_medis = cursor.fetchone()[0]

            cursor.execute(
                'SELECT alergi FROM alergi_pasien WHERE no_rekam_medis = %s',
                (no_rekam_medis,))

            alergi = [x[0] for x in cursor.fetchall()]

        context['data'].update({
            'No. Rekam Medis': no_rekam_medis,
            'Alergi': alergi,
        })

    if request.session.get('role') == 'dokter':
        with connection.cursor() as cursor:
            cursor.execute('SELECT * FROM dokter WHERE username = %s',
                           (request.session['username'],))
            dokter = cursor.fetchone()
        context['data'].update({
            'No. SIP': dokter[2],
            'Spesialisasi': dokter[3],
            })

    return render(request, 'pengguna/profile.html',context)

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            if auth_login(request,form.cleaned_data['username'], form.cleaned_data['password']):
                return redirect('pengguna:profile')
            else:
                form.add_error(None, 'Wrong username or password')
    else:
        form = LoginForm()

    context = {
        'form': form,
        'title': 'Form Login',
        'submit_text': 'Login',
        'links': [{'name': 'register', 'url': reverse('pengguna:register')}],
    }
    return render(request, 'login_form.html', context)


def register(request):
    return render(request, 'pengguna/register.html')


def register_role(request, role):
    if role in register_forms:
        FormClass = register_forms[role]
    else:
        return HttpResponseNotFound('<h1>Role not found</h1>')

    if request.method == 'POST':
        form = FormClass(request.POST)
        if form.is_valid():
            form.save()
            if auth_login(request, form.cleaned_data['username'],
                          form.cleaned_data['password']):
                return redirect('pengguna:profile')
            form.add_error(None, 'Cannot login.')

    else:
        form = FormClass()

    context = {
        'form': form,
        'title': 'Form Pendaftaran %s' % role.title(),
        'target_url': reverse('pengguna:register-role', kwargs={'role': role}),
        'submit_text': 'Daftar',
    }

    if role == 'pasien':
        return render(request, 'pengguna/register_pasien.html', context)
    return render(request, 'tindakan/generic_form.html', context)


def logout(request):
    request.session.flush()
    return redirect('/')


def auth_login(request,username,password):
    with connection.cursor() as cursor:
        cursor.execute('SELECT * FROM PENGGUNA WHERE username=%s AND password=%s',[username,password])
        user=cursor.fetchone()
        if (user != None):
            request.session['email']=user[0]
            request.session['username']=user[1]
            request.session['password']=user[2]
            request.session['nama_lengkap']=user[3]
            request.session['nomor_id']=user[4]
            request.session['tanggal_lahir']=json.dumps(user[5], cls=DjangoJSONEncoder)[1:-1]
            request.session['alamat']=user[6]
            request.session['role']=get_role(username)
            if(request.session['role']=='admin'):
                cursor.execute('SELECT  kode_rs FROM ADMINISTRATOR WHERE username=%s',[username])
                admin=cursor.fetchone()
                request.session['kode_rs']=admin[0]
            elif(request.session['role']=='dokter'):
                cursor.execute('SELECT  id_dokter FROM DOKTER WHERE username=%s',[username])
                dokutah=cursor.fetchone()
                request.session['id_dokter']=dokutah[0]
            else:
                cursor.execute('SELECT  no_rekam_medis FROM PASIEN WHERE username=%s',[username])
                pasien=cursor.fetchone()
                request.session['no_rekam_medis']=pasien[0]
            return True
        else:
            return False

def get_role(username):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM ADMINISTRATOR WHERE username = %s", [username])
        if (cursor.fetchone() != None):
            return "admin"
        cursor.execute("SELECT * FROM DOKTER WHERE username = %s", [username])
        if (cursor.fetchone() != None):
            return "dokter"
        return "pasien"

pengguna/templates/pengguna/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">MEDIKAGO</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'pengguna:profile' %}">Profil</a>
      </li>
      <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle"
          href="#"
          id="navbarDropdown"
          role="button"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          Daftar
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a
            class="dropdown-item"
            href="{% url 'sesi_konsultasi:konsul_form_read' %}"
          >
            Daftar Sesi Konsultasi
          </a>
          <a class="dropdown-item" href="{% url 'tindakan:poli-read'%}">
            Daftar Tindakan Poliklinik
          </a>
          <a class="dropdown-item" href="{% url 'tindakan:read'%}">
            Daftar Tindakan
          </a>
          <a class="dropdown-item" href="{% url 'layanan_poli:layanan_read' %}">Daftar Layanan Poli</a>
          <a class="dropdown-item" href="{% url 'layanan_poli:jadwal_read' %}">Daftar Jadwal Poli</a>
          <a class="dropdown-item" href="{% url 'transaksi:transaksi_read'%}">
            Daftar Transaksi
          </a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle"
          href="#"
          id="navbarDropdown"
          role="button"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          RS Cabang
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{%url 'rs_cabang:rs_form_read' %}">Daftar RS Cabang</a>
          <a class="dropdown-item" href="{%url 'dokter_rscabang:daftar' %}">Daftar Dokter RS Cabang</a>
        </div>
      </li>
    </ul>
    <a
      class="btn btn-sm btn-outline-success"
      href="{% url 'pengguna:logout' %}"
    >
      Logout
    </a>
  </div>
</nav>

pengguna/templates/pengguna/profile.html
{% extends 'base.html' %}
{% load gettype %}

{% block title %}Profil{% endblock %}

{% block content %}
<div class="container">
  <h1>Profile {{ request.session.role|title }}</h1>
  <div>
    {% for key, value in data.items %}
    <div class="row">
      <div class="col-4">{{ key }}</div>
      :
      <div class="col-7">
        {% if value|get_type == "list" %}
        <ul>
          {% for v in value %}
          <li>{{ v }}</li>
          {% endfor %}
        </ul>
        {% else %}
        {{ value }}
        {% endif %}
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

pengguna/templates/pengguna/register.html
<head>
  {% load crispy_forms_tags %}
  {% load static %}
  <title>{{ title }}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
    rel="stylesheet"
    href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"
  />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
    crossorigin="anonymous"
  />
</head>
<body>
  <div class="container">
    <h1 class="d-flex h1 justify-content-center">
      Pilih Role
    </h1>
    <div class="container" >
        <div class="card-deck">
            <div class="w-100 d-none d-md-block d-lg-none"><!-- wrap every 3 on md--></div>
            <div class="card mb-4">
                <img class="card-img-top img-fluid" src="{% static 'img/patient_vector.png'%}" alt="Pasien">
                <div class="card-body">
                    <h4 class="card-title">Pasien</h4><br>
                    <a href="{% url 'pengguna:register-role' 'pasien' %}" class="btn btn-primary">Daftar</a>
                </div>
            </div>
            <div class="w-100 d-none d-md-block d-lg-none"><!-- wrap every 3 on md--></div>
            <div class="card mb-4">
                <img class="card-img-top img-fluid" src="{% static 'img/doctor_vector.png'%}" alt="Dokter" style="max-width:250;top:0;left:0;right:0; bottom:0; width:auto;margin:auto;" >
                <div class="card-body">
                    <h4 class="card-title">Dokter</h4><br>
                    <a href="{% url 'pengguna:register-role' 'dokter' %}" class="btn btn-primary">Daftar</a>
                </div>
            </div>
            <div class="w-100 d-none d-md-block d-lg-none"><!-- wrap every 3 on md--></div>
            <div class="card mb-4">
                <img class="card-img-top img-fluid" src="{% static 'img/admin_vector.png'%}" alt="Admin" width="400" height="400" >
                <div class="card-body">
                    <h4 class="card-title">Administrator</h4><br>
                    <a href="{% url 'admin_rs:form_admin' %}" class="btn btn-primary">Daftar</a>
                </div>
            </div>
        </div>
    </div>
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
  <script
    src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"
  ></script>
</body>

<footer class="page-footer font-small blue">
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="#"> Kelompok 69</a>
  </div>
</footer>

pengguna/templates/pengguna/register_pasien.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
   <style>
        @media only screen and (max-width: 600px) {
            h1{
                font-size: 20px;
            }
        }
    </style>
  {% load crispy_forms_tags %}
  <div class="container">
    <h1 class="d-flex justify-content-center">
      {{ title|default:"form" }}
    </h1>
    {% if links %}
    <div id="links" class="my-3">
      {% for link in links %}
      <a class="btn btn-primary" href="{{ link.url }}">{{ link.name }}</a>
      {% endfor %}
    </div>
    {% endif %}

    <form action="{{ target_url }}" method="POST">
      {% csrf_token %}
      {{ form|crispy }}
      <p>
        Tuliskan alergi disini:
        <input id="add-alergi">
        <button id="add-typed-alergi" class="btn btn-primary">Tambah alergi</button>
      </p>
      <div class="text-center justify-content-center">
        <button type="submit" class="btn-primary btn">
          {{ submit_text|default:"Submit" }}
        </button>
      </div>
    </form>
  </div>
{% endblock %}

{% block script %}
<script src="{% static 'pengguna/register_pasien.js' %}"></script>
{% endblock %}