admin_rs/urls.py
from django.urls import include,path
from .views import form_admin,homepage
app_name='admin_rs'
urlpatterns =[
    path('register/',form_admin,name='form_admin'),
    path('profile/',homepage,name='admin_profile')
    ]

medikago/urls.py
from django.urls import include,path

urlpatterns = [
    path('', include('pengguna.urls')),
    path('rs_cabang/',include('rs_cabang.urls')),
    path('sesi_konsultasi/',include('sesi_konsultasi.urls')),
    path('admin_rs/', include('admin_rs.urls')),
    path('tindakan/', include('tindakan.urls')),
    path('dokter/', include('dokter_rscabang.urls')),
    path('layanan_poli/', include('layanan_poli.urls')),
    path('transaksi/', include('transaksi.urls')),
]

pengguna/urls.py
from django.urls import path
from . import views

app_name = 'pengguna'

urlpatterns = [
    path('', views.general_profile, name='profile'),
    path('redirect/',views.register_redirect,name='redirect'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('register/<str:role>/', views.register_role, name='register-role'),
    path('logout/', views.logout, name='logout'),
]

medikago/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{{ title }} | Medikago 69{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
@media only screen and (max-width: 600px) {
  h1 {
    font-size: 30px;
  }
  p {
    font-size: 10px;
  }
}
body {
  margin-top:72px;
}
    </style>
    {% block style %}{% endblock %}
  </head>
  <body>
    {% if request.session.username %}
    {% if request.session.role == 'admin' %}
      {% include 'navbar-admin.html' %}
    {% else %}
      {% include 'pengguna/navbar.html' %}
    {% endif %}
    {% endif %}

    {% block content %}{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    {% block script %}{% endblock %}
  </body>
  <footer class="page-footer font-small blue">
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="#"> Kelompok 69</a>
  </div>
</footer>
</html>

medikago/templates/base_pengguna.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}{% endblock %} | Medikago - 69</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'base.css' %}" />
  </head>
  <body>
    {% include 'pengguna/navbar.html' %}
    {% block content %}{% endblock %}
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
  <footer class="page-footer font-small blue">
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="#"> Kelompok 69</a>
  </div>
</footer>
</html>

medikago/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}Medikago - 69{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'base.css' %}" />
    <style>
      header {
          max-wdth:2000px;
          max-height:3500px;
          background: black;
          overflow: hidden;
      }

      img {
        object-fit: cover;
        opacity: 0.45;
      }
      section {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        color: #fff;
        font-family: 'Roboto', sans-serif;
      }
      .header{
        font-family: 'Open Sans', sans-serif;
        font-style: normal;
        font-weight: 900;
        letter-spacing: 1px;
        text-transform: uppercase;
      }
      .header2{
        font-family: Roboto, sans-serif;
        font-size: 19px;
        font-style: normal;
        font-weight: 300;
        letter-spacing: normal;
        line-height: 25px;
        text-transform: none;
        color: #FFFFFF;
      }
    </style>
  </head>
  <body>
    <header>
      <img src="{%static 'img/landing.jpeg'%}" alt="Hospital Management">
      <section class='header-text'>

          <h1 class="header">MEDIKAGO</h1>
          <h3 class="header2">Track or manage your medical activity with ease.</h3>
          <h3 class="header2">Anytime, Anywhere.</h3>
          <a class="btn btn-outline-primary" href="{% url 'pengguna:login' %}">Login</a>
          <a class="btn btn-outline-primary ml-3" href="{% url 'pengguna:register' %}">Register</a>
      </section>
    </header>
    <footer class="page-footer font-small blue">
      <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <a href="#"> Kelompok 69</a>
    </div>
  </footer>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>